module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['❗','❤️','🖥️','☇','〽️'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HssGT0vrGU67uzBVFQp9by?mode=ems_copy_c',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://ibb.co/NgPMGW6y.jpg',
    NEWSLETTER_JID: '120363404913442592@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ZORO MD MINI BOT',
    OWNER_NAME: 'SADEE',
    OWNER_NUMBER: '94766748682',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝗣𝗢𝗪𝗘𝗥𝗗 𝗕𝗬 𝗭𝗢𝗥𝗢 𝗠𝗗 𝗠𝗜𝗡𝗜 𝗕𝗢𝗧 ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6PAtxEVccRrRGVEY3j'
};
